### PR TITLE
add KernelSU support

### PR DESCRIPTION
**Pull request by sysuid**
Tested on Sony Xperia 1 V XQ-DQ72, each feature works well.

Android 13
Kernel Ver. 5.15.74-android13-8-g0117d9519ebc #1 Fri Jun 9 20:11:17 UTC 2023
KernelSU Ver. 10994

### CODE REVIEW

**Comment by DavidBerdik** [comment]
I just installed this on my Pixel 6 Pro and it's working for me too.

Android 13
KernelSU 11041
Kernel 5.10.177-android13-4

**Comment by Chainfire** [comment]
Looks good to me, on your heads be it :)

**Review by yurikylekincaide06 — APPROVED** [review]

**Review by yurikylekincaide06 — APPROVED** [review]
.

**Comment by yurikylekincaide06** [comment]
.

**Comment by yurikylekincaide06** [comment]
.

**Review by yurikylekincaide06 — APPROVED** [review]

**Review by yurikylekincaide06 — APPROVED** [review]

**Pull request merged**
